version: '2'
services:
  postgres:
      image: postgres:10.4-alpine
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: donut-shop-db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    ports:
      - 8081:8080
  mongo:
    image: mongo:4.4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: donut-shop-db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo
    ports:
      - "8888:8081"
      
volumes:
  mongodb_data_container: {}







